# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andriy Kravchenko's blog
tagline:          'Senior Web Application Developer'
description:      ''
url:              https://andriy.kravchenko.cc
baseurl:          'https://andriy.kravchenko.cc/'

author:
  name:           'Andriy Kravchenko'
  url:            https://andriy.kravchenko.cc/

paginate:         5
plugins: [jekyll-paginate]